import Head from 'next/head'
import Navbar from '@/components/navbar'
import Rightside from '@/components/rightside'
import { Inter } from 'next/font/google'
import LeftSide from '@/components/leftSide'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title> Prince Konwea</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-screen font-bodyFont bg-bodyColor text-textLight
      overflow-x-hidden overflow-y-scroll'>
        <Navbar/>
        <div className='w-full h-[88vh] xl:flex items-center gap-20 justify-between'>
          <div className='hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0'>
            <LeftSide/>
            </div>
          <div>Middle</div>
          <div className='hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0'>
            <Rightside /> 
          </div>
        </div>
      </main>
    </>
  )
}
